# Example configuration for splunk-ds-camr
refreshInterval: 1m
dryRun: false

destinations:
  dest1: [lane1, lane2]
  dest2: [lane3, lane4]

# wildcard generation settings
wildcard:
  mode: trailingOnly          # or internalNumeric
  minGroupSize: 2             # only wildcard groups with >=2 hosts
  requireMinFixedPrefix: 0    # fixed prefix length before first '*'

cmdb:
  # type can be: dummy | servicenow
  type: dummy
  dummy:
    entries:
      - hostname: abc001
        businessServiceLane: lane1
      - hostname: abc002
        businessServiceLane: lane1
      - hostname: xyz101
        businessServiceLane: lane3
      - hostname: xyz102
        businessServiceLane: lane3
  servicenow:
    baseURL: https://your-instance.service-now.com
    table: cmdb_ci_server
    query: "u_active=true^operational_status=1"
    hostnameField: host_name
    laneField: u_business_service_lane
    pageSize: 200
    timeout: 30s
    insecureSkipVerify: false
    auth:
      # one of: bearerToken or username/password
      bearerToken: ""
      username: ""
      password: ""

serverclass:
  path: ./serverclass.conf
  backup: true
  # app -> serverClass name mapping
  appClass:
    AA-DESTINATION-dest1: AA-DESTINATION-dest1-class
    AA-DESTINATION-dest2: AA-DESTINATION-dest2-class
  # app -> destination key mapping
  appDestination:
    AA-DESTINATION-dest1: dest1
    AA-DESTINATION-dest2: dest2
  # optionally run dry-run for selected apps only (in addition to global dryRun)
  dryRunApps: []

# logging configuration
logging:
  level: info          # debug|info|warn|error
  file: ./camr.log     # log file path
  maxSizeMB: 100       # rotate after this size
  maxBackups: 7        # files to keep
  maxAgeDays: 30       # days to keep
  compress: true       # gzip old logs
  stdout: true         # also log to stdout
